### ISSUE TITLE
钉钉企业内部机器人报错

### ISSUE THREAD

**Issue by ainuoyan** [ineo6/jarvis#1]
你好，请教一下，我使用的是钉钉企业内部机器人，
配置好环境变量后，运行报错，运行日志如下：

```
 .\bin\hubot --name jarvis -a dingtalk
npm WARN jarvis@1.1.0 No repository field.
npm WARN jarvis@1.1.0 No license field.

audited 276 packages in 1.749s
found 0 vulnerabilities

[Mon Feb 17 2020 16:17:43 GMT+0800 (GMT+08:00)] INFO Constructor
[Mon Feb 17 2020 16:17:43 GMT+0800 (GMT+08:00)] INFO Run
[Mon Feb 17 2020 16:17:43 GMT+0800 (GMT+08:00)] ERROR No token or secret is provided to dingtalk!
Set cron event, baidu_weather at 0 0 20 * * *
```

请问改如何配置呢？

**Comment by ineo6** [comment]
可以看下 [hubot-dingtalk](https://github.com/ineo6/hubot-dingtalk) 的说明。

运行是需要以下两个环境变量
```
HUBOT_DINGTALK_AUTH_TYPE=sign
HUBOT_DINGTALK_SECRET=机器人的appSecret
```

**Comment by ainuoyan** [comment]
> 可以看下 [hubot-dingtalk](https://github.com/ineo6/hubot-dingtalk) 的说明。
> 
> 运行是需要以下两个环境变量
> 
> ```
> HUBOT_DINGTALK_AUTH_TYPE=sign
> HUBOT_DINGTALK_SECRET=机器人的appSecret
> ```

我就是设置的这两个变量
![image](https://user-images.githubusercontent.com/14355237/74639769-73106a80-51a9-11ea-9646-a8f462526f7f.png)
我还尝试了node_modules\hubot-dingtalk\dingtalk.js 这两个变量直接赋值，还是不行，同样报错，windows和linux下都试了，同样的输出，太奇怪了😂

**Comment by ineo6** [comment]
不应该啊，你环境变量是配置在哪里了。尝试下执行时，直接在`shell`设置下。

**Comment by ainuoyan** [comment]
> 不应该啊，你环境变量是配置在哪里了。尝试下执行时，直接在`shell`设置下。

配置当前用户的环境变量 ~/.bash_profile
直接echo $HUBOT_DINGTALK_SECRET可以正确打印出来

**Comment by ineo6** [comment]
晕了，是我判断错了，`hubot-dingtalk`发布1.3.1修复了这个问题。

我本地环境变量都配了，结果没有注意到这个问题。

**Comment by ainuoyan** [comment]
> 晕了，是我判断错了，`hubot-dingtalk`发布1.3.1修复了这个问题。
> 
> 我本地环境变量都配了，结果没有注意到这个问题。

成了，大佬厉害，期待大佬的接入主动发消息webhook👍
